### ISSUE TITLE
zenodo settings

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage-archive-2023-02-01#100]
Could the person who set  up zenodo for sagemath please step forward and either remove it from zenodo, or, better fix it so that it works again (the easiest might be to deactivate/activate it).
Unfortunately zenodo does not allow "repo team members" to change the repo settings, it must be done by the same person who set it up.

**Comment by dimpase** [comment]
@haraldschilly

**Comment by haraldschilly** [comment]
I toggled it, but not sure if that helped. I don't see a way to trigger a release from zenodo.

**Comment by dimpase** [comment]
I've just went and edited https://github.com/sagemath/sage/releases/tag/9.1 - this should trigger the update.

If this does not work, it could be we really have to physically remove zenodo integration, and put it up again, not just
toggle, due to stale metadata somewhere not being purged...

**Comment by dimpase** [comment]
all this 
https://github.com/sagemath/sage/settings/hooks/253557611
seem to have no effect on DOI issue

**Comment by dimpase** [comment]
Does zenodo have a "burn all the DOI records etc for for a given repo" option?

**Comment by dimpase** [comment]
fixed by zenodo/zenodo#2055
