### ISSUE TITLE
How to install Sage on Google Colab?

### ISSUE THREAD

**Issue by demining** [sagemath/sage-archive-2023-02-01#102]
I am trying to install **"Sage"** on **Google Colab** via the command:

`!pip install git+https://github.com/sagemath/sage.git`

**I get the error:**

```
Collecting git+https://github.com/sagemath/sage.git
  Cloning https://github.com/sagemath/sage.git to /tmp/pip-req-build-ozlqhlkb
  Running command git clone -q https://github.com/sagemath/sage.git /tmp/pip-req-build-ozlqhlkb
ERROR: File "setup.py" not found for legacy project git+https://github.com/sagemath/sage.git.
```

**No module named 'sage.all_cmdline'**

```
Traceback (most recent call last):
  File "script.py", line 11, in <module>
    from sage.all_cmdline import *   
ModuleNotFoundError: No module named 'sage.all_cmdline'
```

 
Google Colab works on
Description: Ubuntu 18.04.5 LTS
Codename: bionic
model name: AMD EPYC 7B12

pip3 --version
pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

Why can't I install **"Sage"** ? What could be the reasons for this error?

**Comment by koffie** [comment]
This is not the place to ask sage related questions. For that please use https://ask.sagemath.org/

Additionally according to the installation guide https://doc.sagemath.org/html/en/installation/ the recommended way of installing sage on ubuntu is using ubuntu's package manger and not pip.

**Comment by demining** [comment]
@koffie  Please tell me what command you need to set to install all packages **"Sage"** 
Unfortunately, I can not post a question on the site [ask.sagemath.org/questions/ask/ ](ask.sagemath.org/questions/ask/ )because from the moment of registration I have a notification:  **"Could not post, because your karma is insufficient to publish links
Could not post, because your karma is insufficient to publish links"**

**Comment by koffie** [comment]
Well just google `ubuntu install sagemath` and you get a lot of useful hits like https://askubuntu.com/a/1159008/1033768 where they explain you should do something like

```
sudo apt-get install sagemath
```

Needing to point someone who whas linux as part of their username and Tux as their avatar to apt-get feels a bit awkward.

**Comment by mkoeppe** [comment]
In addition to ask.sagemath.org, there are also the Google groups on Sage.

**Comment by slel** [comment]
@sberlinux -- making Sage pip-installable is work in progress, tracked at 

- Sage Trac ticket 29705
  Meta-ticket: Modularize sagelib into separate distributions (pip-installable packages) sagemath-...
  https://trac.sagemath.org/ticket/29705

I have not heard of Sage running on Google Colab so far.
You might want to give CoCalc a try, as Sage works fine there.

New Ask Sage users cannot post links but can add spaces
to disguise them, eg by typing https ://ask .sagemath .org.
