### ISSUE TITLE
sagemath doesn't work w/ Python 3.10.x

### ISSUE THREAD

**Issue by utkarsh2102** [sagemath/sage-archive-2023-02-01#103]
Hello,

Thanks for working on sagemath. Unfortunately, sagemath doesn't build with 3.10.x. Here are the logs:
https://launchpadlibrarian.net/580381333/buildlog_ubuntu-jammy-amd64.sagemath_9.4-3build1_BUILDING.txt.gz

Is it already fixed in the develop branch of something?

**Comment by mkoeppe** [comment]
Yes, see https://wiki.sagemath.org/ReleaseTours
