### ISSUE TITLE
Doesn't compile on MacOS

### ISSUE THREAD

**Issue by acgetchell** [sagemath/sage-archive-2023-02-01#12]
Perhaps it doesn't work with LLVM?

~/sage (master ✓) make
cd spkg && \
    "../spkg/pipestatus" \
        "env SAGE_PARALLEL_SPKG_BUILD='' ./install all 2>&1" \
        "tee -a ../logs/install.log"
/bin/sh: line 0: cd: spkg: No such file or directory
make: **\* [build] Error 1
~/sage (master ✓) gcc -v
Configured with: --prefix=/Applications/Xcode5-DP.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.1.58) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin12.4.0
Thread model: posix

~/sage (master ✓) system_profiler SPSoftwareDataType
Software:

```
System Software Overview:

  System Version: OS X 10.8.4 (12E55)
  Kernel Version: Darwin 12.4.0
  Boot Volume: Macintosh HD
  Boot Mode: Normal
  Secure Virtual Memory: Enabled
  Time since boot: 4:46
```

**Comment by tkluck** [comment]
Thanks for trying this. The `master` branch isn't meant to be compiled at this point, since it contains the currently official sage, which is based on mercurial repositories. You could try the `build_system` branch.
