### ISSUE TITLE
mpfr build fails

### ISSUE THREAD

**Issue by saraedum** [sagemath/sage-archive-2023-02-01#4]
Patching the mpfr sources fails. This is weird because there should be no patches, right?

http://pastebin.com/6pK382HV

**Comment by saraedum** [comment]
this  happened for 713b38555a1879d199a4a804e72428173204fb6c

**Comment by ohanar** [comment]
Use the `working` branch to do your initial build of sage. I should have directions and status of the transition up either later today or tomorrow.

See http://trac.sagemath.org/14781
