### ISSUE TITLE
top-10 plugin has issue with sage (it dosnt counts post view)

### ISSUE THREAD

**Issue by a11231g** [sagemath/sage-archive-2023-02-01#62]
in sage , top-10 plugin doe not counts post views,
i think  this action: " add_action( 'parse_request', 'tptn_parse_request' )" in counter.php file  cause this problem

**Comment by paulmasson** [comment]
This repository is for SageMath. Perhaps you're looking for the WordPress repository:

https://github.com/roots/sage

**Comment by slel** [comment]
This is now https://github.com/roots/sage/issues/1680 -- please close.

**Comment by paulmasson** [comment]
@a11231g Please close this issue.

**Comment by fchapoton** [comment]
please close !
