### ISSUE TITLE
Mode does not follow described behaviour.

### ISSUE THREAD

**Issue by MurrayT** [sagemath/sage-archive-2023-02-01#64]
The `stats.mode(v)` function gives result not complying to documentation when given the list
`[0, 2, 7, 7, 13, 20, 2, 13]`.

The doctsring specifies 

> Return the mode of `v`.  The mode is the **sorted** list of the most
> frequently occuring elements in `v`.  If `n` is the most times
> that any element occurs in `v`, then the mode is the **sorted** list
> of elements of `v` that occur `n` times.

``` sage
sage: mode([0, 2, 7, 7, 13, 20, 2, 13])
[2,13,7]
```

This list returned in this instance is not sorted and therefore `mode(v)` does not meet specification.

**Comment by Mianto** [comment]
#72 When the inputs have same frequency stats.mode returns a sorted list as the doctstring specifies.

**Comment by fchapoton** [comment]
see https://trac.sagemath.org/ticket/21668

**Comment by fchapoton** [comment]
This has been handled in  https://trac.sagemath.org/ticket/21668 and can now be closed.
