### ISSUE TITLE
Including parsed generating functions in the OEIS module

### ISSUE THREAD

**Issue by eluzhnica** [sagemath/sage-archive-2023-02-01#67]
I have parsed about 15k generating functions of the OEIS sequences and as a use case, generated about 300 million relations. It would be great if we could include the generating functions (and maybe even the relations) in the OEIS module. I can provide the gf and relations in a suitable format (e.g Content-MathML).

**Comment by roed314** [comment]
We generally use trac.sagemath.org rather than github to trac issues.  You should open an account there and/or e-mail sage-devel@googlegroups.com to discuss this proposal.

**Comment by fchapoton** [comment]
This issue should be closed, please.

**Comment by slel** [comment]
@eluzhnica did you open an issue on https://trac.sagemath.org ?

**Comment by eluzhnica** [comment]
@slel Thanks for pinging for this! Looks like I never created this since we were planning to go through another channel. Done now: https://trac.sagemath.org/ticket/25405#ticket
