### ISSUE TITLE
Make it clear what this mirror is for

### ISSUE THREAD

**Issue by olexandr-konovalov** [sagemath/sage-archive-2023-02-01#73]
I am watching this repository and there were several new issues/PRs recently- it seems not obvious that this is not a place where they should be submitted, moreover there are already other open issues and PRs. If this is a mirror of the repository and modifying the README file here is not an option, do you think it could help to change the description from "Mirror of the Sage source tree" to something like "Mirror of the Sage source tree (only a mirror - everything must be submitted via https://trac.sagemath.org/)" ?

**Comment by paulmasson** [comment]
@alex-konovalov  +1.  Who can make this change? @vbraun @embray @haraldschilly

**Comment by haraldschilly** [comment]
I've changed the text a bit
