### ISSUE TITLE
sage script multiline parameter parsed error

### ISSUE THREAD

**Issue by ghost** [sagemath/sage-archive-2023-02-01#77]
SageMath version 7.6

for example, I have this in file x.sage:
```
#!/usr/bin/sage
fx(x)=piecewise([[(-1,2),2*x+4], \
        [(2,4), 2*x^2-4*x]])
```
but sage x.sage send error like this
```
  File "x.sage.py", line 7
    __tmp__=var("x"); fx = symbolic_expression(piecewise([[(-_sage_const_1 ,_sage_const_2 ),_sage_const_2 *x+_sage_const_4 ],  * BackslashOperator() * ).function(x)
                                                                                                                               ^
SyntaxError: invalid syntax

```

while I can just copy the code and paste in the sage shell, it works of course.
but for the script, I have no way to make it work, the preparser only deal with a single line and don't know the line continue mark.
 And I'm extremely wondering why the script doesn't work like just paste the content line by line to the sage shell, it's called sage script but it doesn't works like a script.
This can be done just by parsing the original line to the sage shell, which also makes it for sure that the script works really like a script.

**Comment by jdemeyer** [comment]
This is indeed a known issue with the Sage preparser. I guess it's better to write everything on 1 line.

Alternatively, you can first create an expression and then turn it into a function:
```
var('x')
a = piecewise([[(-1,2),2*x+4], \
        [(2,4), 2*x^2-4*x]])
fx(x) = a
```

**Comment by ghost** [comment]
thanks a lot! that's an acceptable solution, indeed
