### ISSUE TITLE
The changelogs on the website and documentation for new 8.0 release.

### ISSUE THREAD

**Issue by abhi18av** [sagemath/sage-archive-2023-02-01#79]
Hi sagemath team :)

I was searching for the changelogs for the sage 8.0 release but it only points to the 7.x release series.

The main thing that I was looking for is whether the Python3 related issues on the track that transition on the tickets, https://trac.sagemath.org/ticket/15980 and https://trac.sagemath.org/ticket/16052 mean that sagemath can now be used as a lib from python3 ?

**Comment by roed314** [comment]
We are working in this direction, but it is not ready yet.  If you'd like to help you're welcome!

Also, we don't use github for active development; it's better to ask a question like this on one of the mailing lists (probably sage-support@googlegroups.com for this one).
