### ISSUE TITLE
Expected Behavior of XOR of Ints

### ISSUE THREAD

**Issue by turnersr** [sagemath/sage-archive-2023-02-01#82]
Hello,

SAGE VERSION: SageMath version 8.0, Release Date: 2017-07-21 

I am trying to understand how XOR works in Sage because it not conform to the logic table:

```print 0 ^ 0, 0 ^ 1 , 1 ^ 0, 1 ^ 1```
results in ```1 0 1 1```
but 
```print (0 + 0) %2, (0 + 1) %2, (1 + 0) %2, (1 + 1) %2```
results in ```0 1 1 0```

And XOR is addition mod 2, so I am not sure what is going on. 

I also tried making everything python ints:

```print int(0) ^ int(0), int(0) ^ int(1) , int(1) ^ int(0), int(1) ^ int(1)```
But I still get ```1 0 1 1```

The only way I have been able to get the result I expect is by:

```
import operator
operator.xor(0, 0), operator.xor(0, 1), operator.xor(1, 0), operator.xor(1, 1)
```
Thank you!

**Comment by roed314** [comment]
The sage preparser chances ^ to exponentiation.
sage: preparse("0^1")
'0**1'

If you want xor, you can do
sage: 6.__xor__(3)
5
David

**Comment by turnersr** [comment]
ok, cool. Thank you!

**Comment by roed314** [comment]
Also note that we use trac.sagemath.org for development and not github: this is just a mirror to clone Sage from.
