### ISSUE TITLE
sage 8.1 crashes 

### ISSUE THREAD

**Issue by afadli** [sagemath/sage-archive-2023-02-01#83]
i have a weird issue where sage crashes on one machine and not on another one even thought they have the same version of OS. 
i installed the gdb for more report, please see attached.
[sage_report.txt](https://github.com/sagemath/sage/files/1713673/sage_report.txt)

**Comment by saraedum** [comment]
@afadli, the SageMath community is not actively monitoring the issues on our GitHub page which is just a mirror of our code repository. We do our development at https://trac.sagemath.org.
There are a number of channels to reach the SageMath community: the [sage-support](https://groups.google.com/forum/#!forum/sage-support) mailing list, the [sage-devel](https://groups.google.com/forum/#!forum/sage-devel) mailing list for development discussion, or https://ask.sagemath.org.
