### ISSUE TITLE
Export worksheets and data from Sage Notebook 6.5 and possible upgrade to latest version

### ISSUE THREAD

**Issue by pguerr061703** [sagemath/sage-archive-2023-02-01#85]
Hello,
I am running an old Sage notebook (version 6.5) on a Redhat Linux 6 server.  I do not have the admin password to log into the notebook. I would like to understand how to 
1) Log into sage dashboard without a password.
2) export worksheets and any other data in this sage notebook
3) upgrade to latest version of sage notebook (version 8.2 ?)
4) Use  a CAPTCHA or throttle invalid login attempts in SAGE notebook
Can anyone please provide me some guidance on how I can tackle these tasks. Would be greatly appreciated.

**Comment by saraedum** [comment]
@pguerr061703, the SageMath community is not actively monitoring the issues on our GitHub page which is just a mirror of our code repository. We do our development at https://trac.sagemath.org, so if you think you've found a bug, please report it there.
Your question is probably best asked on https://ask.sagemath.org or on the [sage-support](https://groups.google.com/forum/#!forum/sage-support) mailing list.
