### ISSUE TITLE
Disable issues

### ISSUE THREAD

**Issue by bekicot** [sagemath/sage-archive-2023-02-01#86]
@sagemath If this is not used as issue tracker, I think the issues feature should be disabled to avoid confussion

**Comment by roed314** [comment]
This sounds like a good idea to me!

**Comment by saraedum** [comment]
@vbraun @embray: I don't have sufficient rights to do so. Could some of you change that in the settings? (and also disable Wiki/Projects.)

**Comment by saraedum** [comment]
Pull Requests can't be disabled but we can discourage them with https://trac.sagemath.org/ticket/25468.

**Comment by saraedum** [comment]
I'd propose to remove the somewhat unfriendly "NO PRs! -- everything must be submitted via https://trac.sagemath.org/" once that ticket has been merged but let's continue the discussion there.

**Comment by saraedum** [comment]
I am closing this. With the next stable release there is going to be a message telling people to create tickets on trac instead here.
