### ISSUE TITLE
Don't detect all cpus with last docker images of sagemath

### ISSUE THREAD

**Issue by lerouxje** [sagemath/sage-archive-2023-02-01#87]
hello,
- with version 8.0 of sagemath/sagemath image docker, i detect all my cpus:
`$ docker run -it --rm sagemath/sagemath:8.0 sage`
SageMath version 8.0, Release Date: 2017-07-21
Forcing sage-location, probably because a new package was installed.
Updating various hardcoded paths...
(Please wait at most a few minutes.)
DO NOT INTERRUPT THIS.
Done updating paths.
sage: `sage.parallel.ncpus.ncpus()`
8

- with version 8.1 and latest i detect only one cpu:
`docker run -it --rm sagemath/sagemath:latest sage`
┌───────────────────────────────────────────────────────────────┐
│ SageMath version 8.2, Release Date: 2018-05-05                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└───────────────────────────────────────────────────────────────┘
Setting permissions of DOT_SAGE directory so only you can read and write it.
sage: `sage.parallel.ncpus.ncpus()`
1

and if i launch "nproc" in container i have all my cpus:
` docker run -it --rm sagemath/sagemath:latest nproc`
8

Can you help me , please

**Comment by saraedum** [comment]
This is not an issue specific to the docker image, the same issue happens for me when I build 8.1+ from scratch.

Please report this issue at https://trac.sagemath.org instead. Sage's developers are not actively monitoring the issues on github.

**Comment by saraedum** [comment]
Feel free to add "saraedum" to the Cc list on the trac ticket. I am happy to have a look at this then.
