### ISSUE TITLE
Not able to install with apt-get

### ISSUE THREAD

**Issue by arisliang** [sagemath/sage-archive-2023-02-01#89]
I tried to run `sudo apt-get install sagemath`. It gives below error under ubuntu 16.04:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package sagemath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'sagemath' has no installation candidate

**Comment by saraedum** [comment]
The Sage developers are not monitoring the issues on github. Please raise your issue again on ask.sagemath.org or on the [sage-support](https://groups.google.com/forum/#!forum/sage-support) mailing list.
