### ISSUE TITLE
Equation solving

### ISSUE THREAD

**Issue by nickedes** [sagemath/sage-archive-2023-02-01#92]
How to use sage to solve equations of variables which are variables of a polynomial ring?

**Comment by saraedum** [comment]
Unfortunately we are not accepting issues on GitHub yet. To report an issue,
please head over to https://trac.sagemath.org, log in with your GitHub account,
and create a ticket there :)

**Comment by slel** [comment]
This is more of a support question. Please ask it at one of the following:
- Ask Sage: https://ask.sagemath.org
- sage-support: https://groups.google.com/forum/#!forum/sage-support
