### ISSUE TITLE
bug in the matrix.pseudoinverse()

### ISSUE THREAD

**Issue by junwei-wang** [sagemath/sage-archive-2023-02-01#93]
Sorry for the title:

I find a bug in the `matrix.pseudoinverse()`

https://github.com/sagemath/sage/blob/9db4320e485ed0aeae56d2c9dfc91fabe14659b1/src/sage/matrix/matrix2.pyx#L1199

Basically, one first decomposes `S = AB` where `rank(A) = rank(B) = rank(S)`.
But in certain circumstances, `B` could be an identity matrix, which makes `S = A`,
`S^+ = (St * S)^(-1) * At` and sometimes `St*S` is not full rank.

For example, the following matrix over GF(2) will fail over this implementation matrix.pseudoinverse()

```
[1 0 0 0 1 0 0 0 0 1]
[0 0 0 0 1 1 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0]
[0 1 1 0 1 1 1 0 1 0]
[0 0 0 1 0 0 1 0 0 0]
[0 1 1 0 1 1 0 0 0 0]
[0 1 0 0 1 0 1 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0]
[0 0 0 1 0 0 1 0 0 1]
[0 0 0 0 1 0 0 1 0 0]
[0 0 0 0 0 0 1 0 0 0]
```

**Comment by saraedum** [comment]
Unfortunately, we are not tracking issues here on github. Please open an issue at trac.sagemath.org (you can login with your github account there as well.)
